workflow:
  version: "1.3.0"
  last_updated: "2026-02-08T14:20:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - UX改善（P0〜P3）の完遂:
        - アクセシビリティ向上: `lang="ja"` の設定、`aria-label` の網羅、`prefers-reduced-motion` 対応。
        - インタラクション改善: ストリーミング停止ボタン、日本語IME誤送信防止、スクロールジャンプ防止。
        - UI/デザインの刷新: 会話履歴の日付別グループ化、カスタム削除確認UI、D&Dの視覚フィードバック、リッチな初期画面（Empty State）。
        - モバイル最適化: `100dvh` 対応、提案チップのスナップスクロール実装。
    - バグ修正: サイドバーの削除ロジックにおける lint エラーや、インライン SVG への移行による依存関係問題の解消。
    
    【次にやること】
    - 会話履歴が長大になった場合のパフォーマンス・監査（仮想スクロールの検討）。
    - DALL-E 3 等の画像生成ツールの統合。
    - ユーザーフィードバックに基づく微調整。

  progress:
    current_phase:
      number: 3
      name: "高度な統合と最適化 (UX完遂)"
      status: "done"
    
    current_task:
      description: "UX評価レポートに基づく全改善項目の実装"
      started_at: "2026-02-08T10:10:00+09:00"
    
    completed_phases:
      - phase: 1
        name: "プロトタイプ構築"
        completed_at: "2026-02-07"
      - phase: 2
        name: "主要機能とGENSPARK準拠対応"
        completed_at: "2026-02-08"
      - phase: 3
        name: "高度な統合と最適化 (UX完遂)"
        completed_at: "2026-02-08"
    
    next_tasks:
      - 大規模会話履歴のパフォーマンスチューニング
      - 画像生成機能の追加
      - プロンプトインジェクション耐性の再検証

  decisions:
    adopted:
      - id: "D001"
        date: "2026-02-07"
        decision: "IndexedDB (Dexie.js) による永続化"
        reason: "ブラウザ単体で完結し、かつオフラインでも高速に履歴を管理するため。"
      - id: "D010"
        date: "2026-02-08"
        decision: "100dvh による iOS サファリ対応"
        reason: "モバイルでのアドレスバーによるレイアウト崩れを防ぎ、常にフルスクリーンを維持するため。"
      - id: "D011"
        date: "2026-02-08"
        decision: "会話履歴の日付別グループ化とカスタム削除UI"
        reason: "履歴の視認性と操作性を向上させ、ブラウザ標準の警告を排除してプレミアム感を出すため。"
      - id: "D012"
        date: "2026-02-08"
        decision: "ドラッグ&ドロップの視覚的ハイライト"
        reason: "ユーザーがファイル添付可能なエリアを直感的に理解できるようにするため。"
      - id: "D013"
        date: "2026-02-08"
        decision: "インライン SVG アイコンへの移行"
        reason: "外部パッケージ依存による開発環境（サンドボックス等）での不具合を避け、プロジェクトの自己完結性を高めるため。"

  features:
    completed:
      - id: "F001"
        name: "会話履歴の永続化"
        status: "done"
      - id: "F003"
        name: "GENSPARK準拠 (maxTokens/mediaResolution)"
        status: "done"
      - id: "F004"
        name: "使用量UI (UsageStats)"
        status: "done"
      - id: "F005"
        name: "自動モード判定（強化版）"
        status: "done"
      - id: "F008"
        name: "UX改善 (P0-P3) パッケージ"
        status: "done"
    
    in_progress: []
    
    planned:
      - id: "F006"
        name: "画像生成ツールの統合"
        status: "planned"

  file_structure:
    created:
      - components/UsageStats.tsx
      - prompt/ARCHITECTURE.yaml
      - prompt/KNOWLEDGE.md
    
    to_create: []
    
    to_modify:
      - app/page.tsx
      - lib/orchestrator.ts
      - lib/mode-detector.ts
      - lib/prompt-builder.ts
      - components/Sidebar.tsx
      - components/InputArea.tsx
      - components/ChatWindow.tsx
      - components/SettingsPanel.tsx

  cautions:
    - "AI SDK v6 の streamText オプション位置（maxTokens 等）がプロバイダー側に移行しているため注意。"
    - "parts ベースの通信を維持しないと Thought Signature で 400 エラーが出る。"
    - "Heroicons の解決エラーを防ぐため、重要な UI 部品はインライン SVG を推奨。"
