workflow:
  version: "1.4.0"
  last_updated: "2026-02-08T17:20:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - Ultimate Chat Revitalization (P1〜P10) の完遂:
        - ファイル処理の抜本的改善: `lib/file-utils.ts` によるMIMEタイプ判定とテキスト解析の信頼性向上。
        - 意図分類の精度向上: 外部ファイル内容を除外した純粋なユーザークエリによるモード判定。
        - オーケストレーション層の刷新: `lib/orchestrator.ts` の AI SDK v6 への完全対応と型安全性の担保。
        - 記憶管理の再構築: IndexedDB操作をクライアントサイドに完全に移行し、`api/summarize` 経由での中期記憶生成を実装。
        - アンチ・ハルシネーション強化: プロンプトエンジニアリングによる「ファイル内容絶対主義」の徹底。
        - ビルド検証: 全TypeScriptエラーを解消し、プロダクションビルドが正常に通ることをユーザー環境で確認。

    【次にやること】
    - 画像生成ツール (DALL-E 3等) の統合。
    - 大規模会話履歴における仮想スクロール等のパフォーマンス改善。
    - プロンプトインジェクションに対する防御層の更なる強化。

  progress:
    current_phase:
      number: 4
      name: "Ultimate Chat Revitalization (信頼性・精度向上)"
      status: "done"
    
    current_task:
      description: "プロダクションビルドの検証と最終ポーリッシュ"
      started_at: "2026-02-08T15:00:00+09:00"
    
    completed_phases:
      - phase: 1
        name: "プロトタイプ構築"
        completed_at: "2026-02-07"
      - phase: 2
        name: "主要機能とGENSPARK準拠対応"
        completed_at: "2026-02-08"
      - phase: 3
        name: "高度な統合と最適化 (UX完遂)"
        completed_at: "2026-02-08"
      - phase: 4
        name: "Ultimate Chat Revitalization (信頼性・精度向上)"
        completed_at: "2026-02-08"
    
    next_tasks:
      - 画像生成機能の追加
      - パフォーマンス・スケーラビリティの監査
      - セキュリティ・ハードニング

  decisions:
    adopted:
      - id: "D020"
        date: "2026-02-08"
        decision: "ファイル内容のテキスト送信フローの確立"
        reason: "ブラウザの `File.text()` を使用してデコードし、プロンプトに明示的に埋め込むことで、Geminiが最も確実に内容を理解できるようにするため。"
      - id: "D021"
        date: "2026-02-08"
        decision: "AI SDK v6 での (tool as any) 回避策の採用"
        reason: "Deep Research 等の複雑なツール定義において、AI SDK 内部の型定義エラーによりビルドが停止するのを防ぐため。ロジックの実行には影響しないことを確認済み。"
      - id: "D022"
        date: "2026-02-08"
        decision: "IndexedDB 操作のクライアントサイド完全移行"
        reason: "サーバーサイド（Next.js API Route）にはブラウザのエンジンがないため、IndexedDBにアクセスするとビルド時や実行時にエラーになる問題を根本解決するため。"

  features:
    completed:
      - id: "F010"
        name: "高精度ファイル解析"
        status: "done"
      - id: "F011"
        name: "分散型要約生成 (Mid-term Memory)"
        status: "done"
      - id: "F012"
        name: "プロダクションビルド・レディ"
        status: "done"
    
    in_progress: []
    
    planned:
      - id: "F020"
        name: "画像生成（DALL-E 3）統合"
        status: "planned"

  file_structure:
    created:
      - lib/file-utils.ts
      - app/api/summarize/route.ts
    
    to_create: []
    
    to_modify:
      - lib/orchestrator.ts
      - lib/mode-detector.ts
      - app/api/chat/route.ts
      - app/page.tsx
      - lib/context-manager.ts

  cautions:
    - "AI SDK v6 は非常に強力だが型定義が厳密（あるいは一部未完成）なため、複雑なツール呼び出しでは `as any` による型キャストが必要になる場合がある。"
    - "IndexedDB (Dexie) の呼び出しを含む `lib` ファイルは、必ず `typeof window !== 'undefined'` のチェックを入れるか、クライアントコンポーネント内からのみ呼び出すこと。"
