workflow:
  version: "1.2.0"
  last_updated: "2026-02-08T08:46:21+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - GENSPARK準拠 (Priority 1 & 2) の実装完了。
    - Thought Signatures の完全保持（partsベースのDB保存・復元実装）。
    - 64k maxTokens 設定、高解像度メディア対応 (mediaResolution)。
    - 「自動判定」モードの追加と InputArea への統合。
    - セッション使用量UI (UsageStats) の実装とページへの統合（リアルタイムコスト表示）。
    - 添付ファイル時の解析プロンプト自動注入機能の追加。
    - highlight.js の github-dark テーマ適用。
    
    【次にやること】
    - 添付ファイルを含めた実環境での最終確認。
    - 「自動判定」モードにおける動的な詳細プロンプト注入ロジックのブラッシュアップ。

  progress:
    current_phase:
      number: 2
      name: "主要機能と準拠対応"
      status: "completed"
    
    current_task:
      description: "GENSPARK準拠対応と使用量UIの実装"
      started_at: "2026-02-08T08:00:00+09:00"
    
    completed_phases:
      - phase: 1
        name: "プロトタイプ構築"
        completed_at: "2026-02-07"
      - phase: 2
        name: "主要機能と準拠対応"
        completed_at: "2026-02-08"
    
    next_tasks:
      - 添付ファイルを含めた実環境での最終確認
      - 「自動判定」モードの詳細ロジック強化

  decisions:
    adopted:
      - id: "D001"
        date: "2026-02-07"
        decision: "IndexedDB (Dexie.js) による永続化"
        reason: "ブラウザ単体で完結し、かつオフラインでも高速に履歴を管理するため。"
      - id: "D002"
        date: "2026-02-07"
        decision: "AI SDK v6 (streamText) の採用"
        reason: "マルチステップツールコールや思考プロセスの容易な取得のため。"
      - id: "D003"
        date: "2026-02-07"
        decision: "検索・URLコンテキストツールの分離"
        reason: "精度向上のため、役割を明確に分けたプロンプト設計を行う。"
      - id: "D004"
        date: "2026-02-08"
        decision: "'auto' モードの追加"
        reason: "ユーザーがモードを意識しなくてもAIが最適なツールを選択できるようにするため。"
      - id: "D005"
        date: "2026-02-08"
        decision: "parts ベースのメッセージ履歴保存"
        reason: "400エラーを防ぎ、Thought Signatures やマルチモーダル情報を完全に保持するため。"
      - id: "D006"
        date: "2026-02-08"
        decision: "UsageStats コンポーネントによるリアルタイムコスト表示"
        reason: "トークン消費量を可視化し、GENSPARK 1.6 準拠とユーザー体験向上のため。"

  features:
    completed:
      - id: "F001"
        name: "会話履歴の永続化"
        status: "done"
      - id: "F002"
        name: "マルチモードチャット（検索/リサーチ/コーディング）"
        status: "done"
      - id: "F003"
        name: "GENSPARK準拠 (maxTokens/mediaResolution)"
        status: "done"
      - id: "F004"
        name: "セッション使用量UI"
        status: "done"
      - id: "F005"
        name: "自動モード判定"
        status: "done"
    
    in_progress: []
    
    planned:
      - id: "F006"
        name: "画像生成ツールの統合"
        status: "planned"

  file_structure:
    created:
      - components/UsageStats.tsx
    
    to_create: []
    
    to_modify:
      - app/page.tsx
      - lib/orchestrator.ts

  cautions:
    - "parts の復元漏れがあるとThought Signatureで400エラーが出るので注意。"
    - "Gemini 3 Flash Preview の API パラメータ仕様変更に追従すること。"
